# Site settings
title: "Miguel Cardona - Students' Work 2005–2018"
email: "hello@miguelcardona.com"
description: "Student Work Produced at the Rochester Institute of Technolgoy New Media Program."
baseurl: "http://students.miguelcardona.com" 
url: "http://students.miguelcardona.com"
twitter_username: miggi
github_username:  gitmiggi

# Build settings
markdown: kramdown
